### PR TITLE
Pat/revamp features

### PR DESCRIPTION
**Pull request by nistadev**
**Description**
Implemented some features for the revamp version such as:
- Sorting for every column
- Design improvement
- Less unnecessary network requests

**Before**
image

**After**
image

### CODE REVIEW

**Comment by AhmedIbrahim336** [comment]
I can't see the changes on the UI. The UI looks different than the one you shared.
<details>
   <summary> Screenshot</summary>
Screen Shot 2022-09-09 at 2 29 17 PM

</details>

**Comment by AhmedIbrahim336** [comment]
I have a couple of notes @nistadev 
1. The sorting from the select menu doesn't work on the `CLASSIC` layout. Try to disable or implement the same thing for the classic layout. 
2. Also the table columns and header are misaligned. 
   - The ℹ️  icon is misaligned 
   - Columns are shifted to the left. 
<details>
   <summary> Screenshot </summary>
Screen Shot 2022-09-09 at 2 37 46 PM

</details>

**Review by AhmedIbrahim336 — CHANGES_REQUESTED** [review]
Please fix flow errors.

**Comment by nistadev** [comment]
> I have a couple of notes @nistadev
> 
> 1. The sorting from the select menu doesn't work on the `CLASSIC` layout. Try to disable or implement the same thing for the classic layout.
> 2. Also the table columns and header are misaligned.
>    
>    * The information_source  icon is misaligned
>    * Columns are shifted to the left.
> 
> Screenshot

Fixed in the pushed commit

**Review by AhmedIbrahim336 — APPROVED** [review]
LGTM. Thanks, @nistadev!

**Pull request merged**
