### PR TITLE
Add revamp adapool list

### PR DESCRIPTION
**Pull request by paulclindo**
Revamp version
Desktop
Screen Shot 2021-11-03 at 1 26 10 AM

Mobile
Screen Shot 2021-11-03 at 1 27 09 AM

### CODE REVIEW

**Comment by Marta-Ryzhok** [comment]
1. Colour of labels
Please double-check colour, they seem to be darker grey but I applied light-grey for labels
image


Here is the reference of three greys I apply for the texts across yoroi.
black primary - ` 900`
grey secondary 1 - ` 600`
light-grey secondary 2 - `400`
the same colours that are provided on the pallet.
reference to incision text styles https://projects.invisionapp.com/d/main#/console/21682093/458875676/inspect

image

**Comment by Marta-Ryzhok** [comment]
2. Stake Pool -> Stake Pools
image

**Comment by Marta-Ryzhok** [comment]
3. On the last call we decided to remove icons (question markets) and just show tooltips when the user hover-over each label.
image

**Comment by Marta-Ryzhok** [comment]
4. Remove `Sort by` select/dropdown. Later on all columns should be sortable, and we will come up with own ranking system. 
5. This` search bar `update won't be implemented yet?
reference from design 
image
image

**Comment by Marta-Ryzhok** [comment]
6. For mobile 
- the same about the Grey colour of labels, too dark
- double-check the text style it seems the labels and values in the Stake Pool's card are medium boldness but should be regular
- please change the button Delegate to just wording style, like on the desktop 
- also just spotted, add paddings between social media icons,  +10 px in between, because now it's gonna be challenging to press on the needed icon.

mobile reference page https://projects.invisionapp.com/d/main#/console/21500065/458210609/preview

**Comment by paulclindo** [comment]
@Marta-Ryzhok 
- Desktop
Screen Shot 2021-11-05 at 2 58 32 AM

- Mobile
Screen Shot 2021-11-05 at 2 57 48 AM

**Review by vsubhuman — APPROVED** [review]

**Pull request merged**
